### ISSUE TITLE
Skills reset

### ISSUE THREAD

**Issue by altacch** [CARVE-ROBMOSYS/BTCompiler#4]
During the 23rd of July meeting the necessity of handling *reset actions* of skills emerged again. There are two ways to implement such actions in our interpreter:

* The first, as suggested by @miccol, is to proceed as follows: every time a child of a Sequence node (which is not the last) returns Running or Fail, we send a "reset message" to each of the following children, indipendently from any previous execution. It is up to the code realizing the individual skills to decide what to do with this reset message (i.e., ignore it if the skill is not running, take the appropriate action otherwise)
* The second, as suggested by @StefanoSoffiaUTRC, is to send the reset messages only when needed (i.e. to previously activated skills). Of course this needs some form of local memory in our representation of Behavior Trees. The simplest way to achieve this is to augment the BT data structure with a field *cached_output* of type *return_enum* which memorizes the previous return value of each node, and then modify slightly the semantics of Sequence and Fallback nodes (I sketched a possible algorithm [on this page](https://github.com/CARVE-ROBMOSYS/BTCompiler/wiki/Reset-messages)).

I have already implemented the first approach in the file [reactive.v](https://github.com/CARVE-ROBMOSYS/BTCompiler/blob/master/reactive.v). The idea is that the implementer specifies a function to be called in order to reset a skill, similar to the `ExecuteSkill` interface we are already using. (The OCaml code is not yet updated to use the new semantics, however.)
The second approach needs a more radical modification of the BT data type, so it would be better to do it in a separate branch.

Comments/remarks?

**Comment by miccol** [comment]
Hi @altacch 
Thank you
About the `cached_output' solution. Isn't that sensitive to low tick frequency? Could it happen that in the time windows between the last tick and the halt the skill has terminated but the BT has not realized that?

**Comment by altacch** [comment]
Of course this is possible, but I don't see why this is a problem for reset messages. The cached information is only used to decide which skills should be reset, not which should be executed. At worst we just send a superflous reset.

**Comment by miccol** [comment]
A superfluous reset could be dangerous if the halt of a skill is not properly configured (by the user). 
For example, if the code in the halt requires access to a resource and the resource is no longer available after the action has terminated (e.g. write on a log file).

I understand this is a very corner case.

**Comment by StefanoSoffiaUTRC** [comment]
I agree with @miccol.

AFAIK the idea was already described and implemented in the ALES proposal of alternative BT formulation included in [this SMV file](https://github.com/CARVE-ROBMOSYS/BTCompiler/blob/master/smv/bt_with_skill_reset.smv).

The approach is the same of the one in the first point from the first post. Basically, each tick visits all the leaves of the BT either enabling or disabling (i.e. reset) them. 

@altacch what you describe in the second point seems to me the discussion we had about the implementation of *starred* operators, which AFAIK is orthogonal to the *skill reset*, but still relevant. Do you have an update about the starred operators?

**Comment by altacch** [comment]
@miccol 
> A superfluous reset could be dangerous if the halt of a skill is not properly configured (by the user).
For example, if the code in the halt requires access to a resource and the resource is no longer available after the action has terminated (e.g. write on a log file).

That's right. In my opinion that would be a bug in the skill implementation, however.
In any case, if there is agreement on this point we can stick to the first solution; it also has the benefit of not requiring major changes in the BT data type. However I expect very little can be formally proved about this implementation, as basically every detail is left to the inner working of the skills (from a computational point of view the `reset` function in `reactive.v` is totally useless, having a `unit` return type).(**Update**: this turned out to be a problem, see comment below)

@StefanoSoffiaUTRC 
> what you describe in the second point seems to me the discussion we had about the implementation of starred operators, which AFAIK is orthogonal to the skill reset, but still relevant. Do you have an update about the starred operators?

Starred nodes are not my priority at the moment (cf. [the wiki page](https://github.com/CARVE-ROBMOSYS/BTCompiler/wiki/Reset-messages)) -- I don't think it is necessary to provide them as primitives since they are trivial to implement via a fallback. We still miss a lot of other stuff though (spec extractor for BTs with arbitrary branching, relation between BTs operational semantics and execution of SMV state machines, integration of contracts, etc.) and the deadline is approaching quickly...

**Comment by StefanoSoffiaUTRC** [comment]
@altacch agreed.

W.r.t. your comment:

> very little can be formally proved about this implementation, as basically every detail is left to the inner working of the skills

I'm not sure I can parse it correctly, but AFAIK the new approach does not diminish the amount of information available to the BT, thus to COQ. Specifically, you know which leaves are active  and which are not.

**Comment by altacch** [comment]
An update on the "reactive interpreter" status: modelling reset functions as terms of type `skillSet -> unit` turned out to be a bit naive. In fact Coq's extraction routines are quite smart, and will erase terms without computational content like our applications of `reset_bt` (no amount of fiddling with extraction options has been able to override this).
So I just pushed another implementation in which reset functions are terms of type `skillSet -> bool`, i.e. they are supposed to return a boolean value which in practise will always be `true` (although we can cook up a meaning for `false`, e.g. "the reset has not succeeded and we should return Fail"). This implementation survives program extraction, so (**update 27/7**) I was indeed able to integrate it in a straightforward way into the interpreter. :fireworks: 
The version with reset support is currently in the file `int2.ml`; eventually this will become the default implementation.

**Comment by altacch** [comment]
I have just switched the implementation with reset support as the default interpreter. Current (final?) organization of the `infra` directory is:
- `interp.ml`: interpreter with reset support
- `int-wo-res.ml`: old version (kept for reference purposes only)
