### ISSUE TITLE
Semantics equivalence proof in COQ.

### ISSUE THREAD

**Issue by StefanoSoffiaUTRC** [CARVE-ROBMOSYS/BTCompiler#8]
The following lists the ALES comments to equivalence proof sketched by @altacch, that we reviewed together (Loris, Stefano, and Alberto) in the meeting of November 8 2018.

In the order we discussed them in the meeting:

1. Use finite lists instead of streams to model semantics of BT for repeated tick events.
   Negligible issue because this is currently not used for the equivalence proof, which is based on the semantics of the single tick.
2. Use of library "LIST" type definition instead of the current hand-written solution. @altacch rationale for this is that it simplifies proofs because of "nested inductive types".
   Although, library lists would improve readability and standard proof strategies exist for them.
   (Still a minior issue, because in the end this is syntactic sugar and the difference has limited impact.)
3. To represent the state of micro-SMV (or "store"), consider the use of "MAP" type from the COQ standard library (var_name -> var_value) instead of the current approach which leverages lists and the implicit variable ordering generated by the custom function that extracts the variables from a given SMV specification.
   (A different approach might be even better, see later.)
4. To specify the SMV initial state and transition function in COQ, prefer a function to a relation, i.e. instead of:

		init: SMV -> STATE -> boolean
		trans: SMV -> STATE -> STATE -> boolean
		
	it shall be used

		init: SMV -> STATE
		trans: SMV -> STATE -> STATE
		
	This approach would leverage COQ typing system to prove that "SMV initialization and transition are deterministic".
	(Major issue since AFAIK this is something still to be proved with the current formulation.)
5. SMV semantics specification. The current approach to represent the state of a SMV is a list of strings.
   We suggest to define an inductive type as the sum of the base types required to represent the SMV (bool, integers, ....) and then use a list of this inductive type to represent the SMV state.
   Strings do not allow case-analysis, having such inductive type would simplify the proof by enabling case-analysis proof.
   (Why are string needed to represent the SMV state, i.e. SMV variable values which are either booleans or natural numbers?)
   (We feel this can be a major issue in advancing with the proof.)
   
All the previous notes are somehow "bottom-up" observations collected during the review of the COQ files. The following one is instead our current best shot at how we believe the equivalence proof should be constructed, at an high level.
The current approach to define the SMV state and evaluate the transition function "flattens" the hierarchical structure of the SMV generated from the BT, i.e. it removes the module hierachy. We believe this is counterproductive.

Both the SMV state and transition function shall instead be defined to preserve the same hierarchical structure of the SMV, thus of the BT.
This would enable a proof by structural induction on the BT that can leverage as the inductive hypotesis the equivalence of the children nodes.

@altacch  and @artac72, feedbacks?

**Comment by altacch** [comment]
Re point 2: for more about the subtleties of nested inductive types see [Adam Chlipala's book](http://adam.chlipala.net/cpdt/), section 3.8. I will add a pointer to this in the next update of deliverable D5.1.

Re point 4: the problem with this approach is that a SMV module may specify a FSM which is *not* deterministic. See e.g. the module `ex1` in the examples at the end of fsm.v. So either you define in some way a type of "surely deterministic" smv modules, or else your function converting an `smv_module` to a transition function will not be total.

Re point 5: this is surely an approach worth considering. However it seems to me that strings are unavoidable, unless you decide to "code" in some way the symbolic constants appearing in the (user-specified) micro-smv module as terms of some other (inductive) type.

**Comment by altacch** [comment]
In the end we settled for an informal proof of equivalence (see D5.1 document)
